Refine cleaning steps with more orgs
adding spring-music route which was reported as leaking:

API endpoint:   [secure] (API version: 2.103.0)
User:           [secure]
Org:            pcfdev-org
Space:          pcfdev-space
ERROR: The acceptance environment contains some residual routes, run "cf routes" - please clean them up using a PR on clean.sh
Getting routes for org pcfdev-org / space pcfdev-space as [secure] ...
space          host           domain                       port   path   type   apps   service
pcfdev-space   spring-music   [secure]